version: "3.8"
services:

  # Service Provider
  sp-orionld:
    container_name: sp-orionld
    image: fiware/orion-ld:latest
    command: "-dbhost sp-orionld-mongo -port 1026"
    ports:
      - "1027:1026"
    links:
      - sp-orionld-mongo
    networks:
      - local_network

  sp-orionld-mongo:
    container_name: sp-orionld-mongo
    image: mongo:4.4
    command: "--nojournal"
    volumes:
      - SP_ORIONLD:/data/db
      - SP_ORIONLD_DBCONFIG:/data/configdb
    networks:
      - local_network

  sp-blockchain-connector-orionld-intf:
    container_name: sp-blockchain-connector-orionld-intf
    image: blkconn-orionld-intf
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8081:8080"
    volumes:
      - ./sp-config.yml:/src/main/resources/custom-config.yml
    networks:
      - local_network

  sp-blockchain-connector-node-intf:
    container_name: sp-blockchain-connector-node-intf
    image: blkconn-node-intf
    ports:
      - "8083:8080"
    networks:
      - local_network

  sp-blockchain-connector-core:
    container_name: sp-blockchain-connector-core
    image: blkconn-core
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8082:8080"
    volumes:
      - ./sp-config.yml:/src/main/resources/integration-config.yml
    links:
      - sp-blockchain-connector-orionld-intf
      - sp-blockchain-connector-node-intf
    networks:
      - local_network

  # Marketplace 1
  mkt1-orionld:
    container_name: mkt1-orionld
    image: fiware/orion-ld:latest
    command: "-dbhost mkt1-orionld-mongo -port 1026"
    ports:
      - "1028:1026"
    links:
      - mkt1-orionld-mongo
    networks:
      - local_network

  mkt1-orionld-mongo:
    container_name: mkt1-orionld-mongo
    image: mongo:4.4
    command: "--nojournal"
    volumes:
      - MKT1_ORIONLD:/data/db
      - MKT1_ORIONLD_DBCONFIG:/data/configdb
    networks:
      - local_network

  mkt1-blockchain-connector-orionld-intf:
    container_name: mkt1-blockchain-connector-orionld-intf
    image: blkconn-orionld-intf
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8085:8080"
    volumes:
      - ./mkt1-config.yml:/src/main/resources/custom-config.yml
    networks:
      - local_network

  mkt1-blockchain-connector-node-intf:
    container_name: mkt1-blockchain-connector-node-intf
    image: blkconn-node-intf
    ports:
      - "8087:8080"
    networks:
      - local_network

  mkt1-blockchain-connector-core:
    container_name: mkt1-blockchain-connector-core
    image: blkconn-core
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8084:8080"
    volumes:
      - ./mkt1-config.yml:/src/main/resources/integration-config.yml
    links:
      - mkt1-blockchain-connector-orionld-intf
      - mkt1-blockchain-connector-node-intf
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  SP_ORIONLD:
  SP_ORIONLD_DBCONFIG:
  MKT1_ORIONLD:
  MKT1_ORIONLD_DBCONFIG: