version: "3.8"
services:

  # Blockchain Connector
  blockchain-connector-2:
    container_name: blockchain-connector-2
    image: blockchain-connector
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "3311:3310"
    networks:
      - local_net

  blockchain-connector:
    container_name: blockchain-connector
    image: blockchain-connector
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "3310:3310"
    networks:
      - local_net


networks:
  local_net:
